name: actions
on: [push]
jobs: 
  my-new-job:
    runs-on: ubuntu-latest 
    steps:
      - name: "check checkout action" 
        uses: actions/checkout@v2.5.0
      - name: "test_action"
        id: "test_id"
        uses: actions/hello-world-javascript-action@v1
        with:  
          who-to-greet: muly max
      - name: "test2"
        run: |
          echo "${{ steps.test_id.outputs.time }}"
          ls -la
