name: shell commands
on: [push] 
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo shell command
        run: echo "my test"
      - name: multi line script
        run: |
          echo "npm -v:"
          npm -v
          echo "cat"
          cat
          echo "node -v-3" 
          node -v
      - name: run python command
        run: |
          import platform
          print(platform.processors())
        shell: python
        