name: shell commands
on: [push] 
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo shell command
        run: echo "my test"
      - name: multi line script
        run: |
          echo "npm -v:"
          npm -v
          echo "cat"
          ls -la
          echo "node -v-3" 
          node -v
      - name: run python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-machine:
    runs-on: windows-latest
    steps:
      - name: powershell-command
        run: Get-Location
        shell: powershell

      - name: bash-command
        run: pwd
        shell: bash      

        